[package]
name = "neorg-task-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-tasks1 = "5.0.2"
hyper = { version = "0.14.26", features = ["http2", "client"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
tokio = { version = "1.28.0", features = ["full"] }
yup-oauth2 = "8.3.0"
